# Generated by Django 4.0.6 on 2022-08-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inspection_defect_location_part_img_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(choices=[('Damage', 'Handling Damage'), ('Delamination', 'Delamination'), ('Ecoat Texture', 'Ecoat Texture'), ('File Marks', 'File Marks')], max_length=200)),
                ('defect_location', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='partinstance',
            name='operator',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partinstance',
            name='stage',
            field=models.CharField(choices=[('pre-paint', 'Pre-paint inspection'), ('final', 'Final inspection'), ('Other', 'Other')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinstance',
            name='status',
            field=models.CharField(choices=[('ok', 'Passed'), ('q', 'Quarantine'), ('r', 'Rework'), ('s', 'Scrap')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
