# Generated by Django 4.0.6 on 2022-08-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_part_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinstance',
            name='operator',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partinstance',
            name='part_origin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partinstance',
            name='stage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partinstance',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
