# Generated by Django 4.0.6 on 2022-08-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_partinstance_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinstance',
            name='part_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_instance', to='api.part'),
        ),
    ]
