# Generated by Django 4.0.6 on 2022-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_partinstance_part_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partinstance',
            name='status',
        ),
        migrations.AddField(
            model_name='defect',
            name='status',
            field=models.CharField(default='OK', max_length=200),
        ),
    ]
