# Generated by Django 4.0.6 on 2022-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_partinstance_status_defect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='operator',
            field=models.CharField(default=' ', max_length=80),
        ),
    ]
