# Generated by Django 4.0.6 on 2022-08-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_defect_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partinstance',
            name='operator',
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_name',
            field=models.CharField(max_length=200),
        ),
    ]
