# Generated by Django 4.0.6 on 2022-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_partinstance_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_location',
            field=models.JSONField(max_length=10),
        ),
    ]
