# Generated by Django 4.0.6 on 2022-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_defect_defect_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
