# Generated by Django 4.0.6 on 2022-08-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_defect_defect_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
