# Generated by Django 4.0.6 on 2022-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_defect_defect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinstance',
            name='serial_number',
            field=models.CharField(max_length=11),
        ),
    ]
