# Generated by Django 4.0.6 on 2022-08-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FG_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('part_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pre-paint', 'Pre-paint inspection'), ('final', 'Final inspection'), ('Other', 'Other')], max_length=200)),
                ('status', models.CharField(choices=[('ok', 'Passed'), ('q', 'Quarantine'), ('r', 'Rework'), ('s', 'Scrap')], max_length=200)),
                ('defect', models.CharField(choices=[('Damage', 'Handling Damage'), ('Delamination', 'Delamination'), ('Ecoat Texture', 'Ecoat Texture'), ('File Marks', 'File Marks')], max_length=200)),
                ('part_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partinstance')),
            ],
        ),
    ]
