# Generated by Django 4.0.6 on 2022-08-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['FG_code']},
        ),
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
    ]
