# Generated by Django 4.0.6 on 2022-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inspection_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='defect_location',
            field=models.CharField(default=(0, 0), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='img_reference',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='operator',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
