# Generated by Django 4.0.6 on 2022-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_defect_part_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='img_reference',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
